### ISSUE TITLE
Hacktoberfest 2021's logo is too large

### ISSUE THREAD

**Issue by saswatsamal** [AnshumanFauzdar/Hacktoberfest2021#25]
![image](https://user-images.githubusercontent.com/39031660/136132169-b3b441e6-1888-4358-8b76-90d36286ecfe.png)

The hacktoberfest logo is very large, and it is not looking good. I can work on fixing it and making the UI look good.
Please assign the work to me.

**Comment by saswatsamal** [comment]
Can you please assign this to me?

**Comment by AnshumanFauzdar** [comment]
Fork this repo and start working @saswatsamal

**Comment by hackgone** [comment]
@AnshumanFauzdar just made changes in css .please check it.
